### ISSUE TITLE
[Skylab] Init of the Lib runs on the Main thread

### ISSUE THREAD

**Issue by Yuri-Kuchinskiy** [AppLozic/Applozic-Chat-iOS-Framework#59]
@Sander-Kornev please add more info on this one

**Comment by Sander-Kornev** [comment]
_I'll copy the description from the email_

All work with CoreData is done in the main thread. I meant calls like 
```
[theDBHandler.managedObjectContext save:&error];
NSArray *fetchedObjects = [theDBHandler.managedObjectContext executeFetchRequest:fetchRequest error:&error];
```

Because of this user with lots of groups has their UI frozen on the app launch. It might take several seconds or even more on old devices.
Just to name a few here are some heavy methods

ALChannelDBService
```
-(DB_CHANNEL_USER_X *)getChannelUserXByUserId:(NSNumber* )channelKey andUserId:(NSString *) userId
-(void)insertChannelUserX:(NSMutableArray *)channelUserXList
```

**Please, optimize work with CoreData and push it to a background thread.**

**Comment by Sunilkumarr** [comment]
Thanks for sharing the details. As this requires a lot of changes and it might break some of our APIs so we can't commit any date for when we'll release. We will explore it and let you know when we do this change.

**Comment by Yuri-Kuchinskiy** [comment]
@Sunilkumarr we need to know when you will be able to estimate, how long do you need for the estimation?

we should not leave tickets open which impact our clients, and this one does

Why this should impact the api? the same initialization possible on Android sdk with no issues. We cant have our users to wait 30 - 45 sec to app to load, they think that it is bug and kill the app

**Comment by Sander-Kornev** [comment]
@Sunilkumarr Hi
I've sent an email to Applozic Support with the topic "[Skylab] iOS SDK freezes for several minutes at login". Please, take a look. 
It seems that the issue is the same as here.

**Comment by mukeshthawani** [comment]
We have fixed this issue in our latest beta release.
